"""add delivery to orders

Revision ID: 08379e1ebf5f
Revises: 911750ea2d86
Create Date: 2026-09-11 09:06:19.819151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08379e1ebf5f'
down_revision: Union[str, Sequence[str], None] = '911750ea2d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_method_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'delivery_methods', ['delivery_method_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_method_id')
    # ### end Alembic commands ###
