"""add promo code restrictions

Revision ID: 2047d76e897d
Revises: 03f27a9a5323
Create Date: 2026-09-11 21:42:01.945860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2047d76e897d'
down_revision: Union[str, Sequence[str], None] = '03f27a9a5323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_codes', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('promo_codes', sa.Column('min_order_amount', sa.Integer(), server_default='0', nullable=False))
    op.add_column('promo_codes', sa.Column('max_uses', sa.Integer(), nullable=True))
    op.add_column('promo_codes', sa.Column('used_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_codes', 'used_count')
    op.drop_column('promo_codes', 'max_uses')
    op.drop_column('promo_codes', 'min_order_amount')
    op.drop_column('promo_codes', 'expires_at')
    # ### end Alembic commands ###
