"""add promo code to orders

Revision ID: 2f38a53e19de
Revises: 0628763f0543
Create Date: 2026-09-11 05:49:21.558474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f38a53e19de'
down_revision: Union[str, Sequence[str], None] = '0628763f0543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('promo_code', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('discount_percent', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount_percent')
    op.drop_column('orders', 'promo_code')
    # ### end Alembic commands ###
