"""add shipment events

Revision ID: 3251ab03cb7d
Revises: c19c0de54abc
Create Date: 2026-09-11 12:18:27.887677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3251ab03cb7d'
down_revision: Union[str, Sequence[str], None] = 'c19c0de54abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_events_id'), 'shipment_events', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_events_order_id'), 'shipment_events', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_events_order_id'), table_name='shipment_events')
    op.drop_index(op.f('ix_shipment_events_id'), table_name='shipment_events')
    op.drop_table('shipment_events')
    # ### end Alembic commands ###
