"""add order item line total

Revision ID: 893cd1973e3c
Revises: ec31346f3d77
Create Date: 2026-09-11 10:22:07.319805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893cd1973e3c'
down_revision: Union[str, Sequence[str], None] = 'ec31346f3d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('line_total', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'line_total')
    # ### end Alembic commands ###
