"""add delivery methods

Revision ID: 911750ea2d86
Revises: 1deb2d783a5d
Create Date: 2026-09-11 08:46:43.381959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911750ea2d86'
down_revision: Union[str, Sequence[str], None] = '1deb2d783a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_delivery_methods_price_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_methods_code'), 'delivery_methods', ['code'], unique=True)
    op.create_index(op.f('ix_delivery_methods_id'), 'delivery_methods', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_methods_id'), table_name='delivery_methods')
    op.drop_index(op.f('ix_delivery_methods_code'), table_name='delivery_methods')
    op.drop_table('delivery_methods')
    # ### end Alembic commands ###
