"""add delivery snapshot fields

Revision ID: 91407d534e3a
Revises: 08379e1ebf5f
Create Date: 2026-09-11 09:16:55.606532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91407d534e3a'
down_revision: Union[str, Sequence[str], None] = '08379e1ebf5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_method_code', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('delivery_method_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('delivery_price', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_price')
    op.drop_column('orders', 'delivery_method_name')
    op.drop_column('orders', 'delivery_method_code')
    # ### end Alembic commands ###
