"""add shipping address to orders

Revision ID: 91471f3b6f9a
Revises: 42c82bb5e7ed
Create Date: 2026-09-11 05:05:31.339418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91471f3b6f9a'
down_revision: Union[str, Sequence[str], None] = '42c82bb5e7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_city', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_street', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_street')
    op.drop_column('orders', 'shipping_city')
    # ### end Alembic commands ###
