"""add shipment tracking history

Revision ID: ab10e7703ddf
Revises: 3251ab03cb7d
Create Date: 2026-09-11 15:24:23.038746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab10e7703ddf'
down_revision: Union[str, Sequence[str], None] = '3251ab03cb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_tracking_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('shipping_carrier', sa.String(length=100), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_tracking_history_id'), 'shipment_tracking_history', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_tracking_history_order_id'), 'shipment_tracking_history', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_tracking_history_order_id'), table_name='shipment_tracking_history')
    op.drop_index(op.f('ix_shipment_tracking_history_id'), table_name='shipment_tracking_history')
    op.drop_table('shipment_tracking_history')
    # ### end Alembic commands ###
