"""add price drop notifications

Revision ID: e3b94b0e801f
Revises: ae53868f806c
Create Date: 2026-09-11 06:43:51.031733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b94b0e801f'
down_revision: Union[str, Sequence[str], None] = 'ae53868f806c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_drop_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Integer(), nullable=False),
    sa.Column('new_price', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_drop_notifications_id'), 'price_drop_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_price_drop_notifications_product_id'), 'price_drop_notifications', ['product_id'], unique=False)
    op.create_index(op.f('ix_price_drop_notifications_user_id'), 'price_drop_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_drop_notifications_user_id'), table_name='price_drop_notifications')
    op.drop_index(op.f('ix_price_drop_notifications_product_id'), table_name='price_drop_notifications')
    op.drop_index(op.f('ix_price_drop_notifications_id'), table_name='price_drop_notifications')
    op.drop_table('price_drop_notifications')
    # ### end Alembic commands ###
