"""add order totals breakdown

Revision ID: ec31346f3d77
Revises: b8a7a0a18beb
Create Date: 2026-09-11 10:05:32.421045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec31346f3d77'
down_revision: Union[str, Sequence[str], None] = 'b8a7a0a18beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('subtotal', sa.Integer(), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('discount_amount', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'subtotal')
    # ### end Alembic commands ###
