"""add order shipment tracking

Revision ID: faccc434951f
Revises: 893cd1973e3c
Create Date: 2026-09-11 10:54:37.575500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faccc434951f'
down_revision: Union[str, Sequence[str], None] = '893cd1973e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_carrier', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('tracking_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tracking_number')
    op.drop_column('orders', 'shipping_carrier')
    # ### end Alembic commands ###
