"""Create users table

Revision ID: fea89a64123c
Revises: 0e40a069490f
Create Date: 2026-09-11 00:12:51.409307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea89a64123c'
down_revision: Union[str, Sequence[str], None] = '0e40a069490f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id")
    )

    op.create_index(
        op.f("ix_users_email"),
        "users",
        ["email"],
        unique=True
    )

    op.create_index(
        op.f("ix_users_id"),
        "users",
        ["id"],
        unique=False
    )

    op.create_index(
        op.f("ix_users_username"),
        "users",
        ["username"],
        unique=True
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
